# Generated by Django 3.1.2 on 2020-10-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20201023_0015'),
        ('core', '0009_auto_20201022_2000'),
    ]

    operations = [
    ]
